# sta.tcl - Generic OpenROAD Static Timing Analysis script
# Usage: openroad -exit sta.tcl

# Check for required environment variables
set required_vars {DESIGN_NAME LIB_FILES VERILOG_FILE SPEF_FILE SDC_FILE OUTPUT_DIR}
foreach var $required_vars {
    if {![info exists ::env($var)]} {
        puts "Error: Environment variable $var is not set."
        exit 1
    }
}

# Optional OUTPUT_SUFFIX for distinguishing RL from SA output files (e.g., "_rl")
if {[info exists ::env(OUTPUT_SUFFIX)]} {
    set output_suffix $::env(OUTPUT_SUFFIX)
} else {
    set output_suffix ""
}

set design_name $::env(DESIGN_NAME)

# 1. Read Inputs
puts "\[STA\] Reading design files..."

# Read LEF files first (required for technology information)
# Check for MERGED_LEF or LEF_FILES
if {[info exists ::env(MERGED_LEF)] && [file exists $::env(MERGED_LEF)]} {
    puts "  Reading Merged LEF: $::env(MERGED_LEF)"
    read_lef $::env(MERGED_LEF)
} elseif {[info exists ::env(LEF_FILES)]} {
    foreach lef [split $::env(LEF_FILES) " "] {
        if {[file exists $lef]} {
            puts "  Reading LEF: $lef"
            read_lef $lef
        } else {
            puts "Warning: LEF file $lef not found"
        }
    }
} elseif {[info exists ::env(TECH_LEF)] && [file exists $::env(TECH_LEF)]} {
    puts "  Reading Tech LEF: $::env(TECH_LEF)"
    read_lef $::env(TECH_LEF)
} else {
    puts "Warning: No LEF file provided. STA may work but technology info may be missing."
    puts "  Set MERGED_LEF, LEF_FILES, or TECH_LEF environment variable"
}

# Read Liberty files
foreach lib [split $::env(LIB_FILES) " "] {
    if {[file exists $lib]} {
        puts "  Reading Liberty: $lib"
        read_liberty $lib
    } else {
        puts "Error: LIB file $lib not found"
        exit 1
    }
}

# Read Verilog
if {[file exists $::env(VERILOG_FILE)]} {
    puts "  Reading Verilog: $::env(VERILOG_FILE)"
    read_verilog $::env(VERILOG_FILE)
} else {
    puts "Error: Verilog file $::env(VERILOG_FILE) not found"
    exit 1
}

# Link Design (requires LEF to be read first)
puts "  Linking design..."
link_design $design_name

# Read SPEF file (parasitic information)
if {[file exists $::env(SPEF_FILE)]} {
    puts "  Reading SPEF: $::env(SPEF_FILE)"
    read_spef $::env(SPEF_FILE)
} else {
    puts "Warning: SPEF file $::env(SPEF_FILE) not found"
    puts "Warning: Timing analysis will be inaccurate without parasitic information"
}

# Read SDC file (timing constraints)
if {[file exists $::env(SDC_FILE)]} {
    puts "  Reading SDC: $::env(SDC_FILE)"
    read_sdc $::env(SDC_FILE)
} else {
    puts "Error: SDC file $::env(SDC_FILE) not found"
    exit 1
}

# 2. Perform Static Timing Analysis
puts "\[STA\] Running Static Timing Analysis..."

# Setup timing report
set setup_rpt $::env(OUTPUT_DIR)/${design_name}${output_suffix}_setup.rpt
puts "  Generating setup timing report: $setup_rpt"
if {[catch {
    set fp [open $setup_rpt w]
    puts $fp "# Setup Timing Report for $design_name"
    puts $fp "# Generated by sta.tcl"
    puts $fp ""
    
    # Get timing metrics
    if {[catch {set wns [sta::worst_slack_cmd max]} err]} {
        puts $fp "WNS: Unable to calculate"
    } else {
        puts $fp "Worst Negative Slack (WNS): $wns ns"
    }
    
    if {[catch {set tns [sta::total_negative_slack_cmd max]} err]} {
        puts $fp "TNS: Unable to calculate"
    } else {
        puts $fp "Total Negative Slack (TNS): $tns ns"
    }
    
    puts $fp ""
    puts $fp "# Detailed timing paths:"
    puts $fp "# Run the following command in OpenROAD for detailed paths:"
    puts $fp "#   report_checks -path_delay max -format full_clock_expanded -digits 3 -nworst 100"
    puts $fp ""
    
    # Try to get worst paths using report_checks
    close $fp
    
    # Run report_checks and append to file
    set cmd "report_checks -path_delay max -format full_clock_expanded -digits 3 -nworst 100"
    if {[catch {eval $cmd} result]} {
        # Command failed, try without nworst
        set cmd "report_checks -path_delay max -format full_clock_expanded -digits 3"
        if {[catch {eval $cmd} result2]} {
            puts "    Warning: Could not generate detailed paths"
        } else {
            set fp [open $setup_rpt a]
            puts $fp $result2
            close $fp
        }
    } else {
        set fp [open $setup_rpt a]
        puts $fp $result
        close $fp
    }
    
    puts "    Setup timing report generated"
} error_msg]} {
    puts "    Warning: Setup timing report generation had issues: $error_msg"
}

# Hold timing report
set hold_rpt $::env(OUTPUT_DIR)/${design_name}${output_suffix}_hold.rpt
puts "  Generating hold timing report: $hold_rpt"
if {[catch {
    set fp [open $hold_rpt w]
    puts $fp "# Hold Timing Report for $design_name"
    puts $fp "# Generated by sta.tcl"
    puts $fp ""
    
    # Get timing metrics
    if {[catch {set wns [sta::worst_slack_cmd min]} err]} {
        puts $fp "WNS: Unable to calculate"
    } else {
        puts $fp "Worst Negative Slack (WNS): $wns ns"
    }
    
    if {[catch {set tns [sta::total_negative_slack_cmd min]} err]} {
        puts $fp "TNS: Unable to calculate"
    } else {
        puts $fp "Total Negative Slack (TNS): $tns ns"
    }
    
    puts $fp ""
    puts $fp "# Detailed timing paths:"
    puts $fp "# Run the following command in OpenROAD for detailed paths:"
    puts $fp "#   report_checks -path_delay min -format full_clock_expanded -digits 3 -nworst 100"
    puts $fp ""
    
    close $fp
    
    # Try to get worst paths
    set cmd "report_checks -path_delay min -format full_clock_expanded -digits 3 -nworst 100"
    if {[catch {eval $cmd} result]} {
        set cmd "report_checks -path_delay min -format full_clock_expanded -digits 3"
        if {[catch {eval $cmd} result2]} {
            puts "    Warning: Could not generate detailed paths"
        } else {
            set fp [open $hold_rpt a]
            puts $fp $result2
            close $fp
        }
    } else {
        set fp [open $hold_rpt a]
        puts $fp $result
        close $fp
    }
    
    puts "    Hold timing report generated"
} error_msg]} {
    puts "    Warning: Hold timing report generation had issues: $error_msg"
}

# Clock skew report
set skew_rpt $::env(OUTPUT_DIR)/${design_name}${output_suffix}_clock_skew.rpt
puts "  Generating clock skew report: $skew_rpt"
if {[catch {
    set fp [open $skew_rpt w]
    puts $fp "# Clock Skew Report for $design_name"
    puts $fp "# Generated by sta.tcl"
    puts $fp ""
    close $fp
    
    # Try to get clock skew information
    if {[catch {report_clock_skew} result]} {
        set fp [open $skew_rpt a]
        puts $fp "Note: Clock skew reporting may not be available or clock tree synthesis may not have been performed."
        puts $fp "Error: $result"
        close $fp
    } else {
        set fp [open $skew_rpt a]
        puts $fp $result
        close $fp
    }
    
    puts "    Clock skew report generated"
} error_msg]} {
    puts "    Warning: Clock skew report failed: $error_msg"
    set fp [open $skew_rpt w]
    puts $fp "# Clock Skew Report for $design_name"
    puts $fp "# ERROR: Could not generate clock skew report"
    puts $fp "# Error: $error_msg"
    puts $fp ""
    puts $fp "# Note: Clock skew information may not be available in this OpenROAD version"
    puts $fp "# or clock tree synthesis may not have been performed"
    close $fp
}

# Additional timing summaries
set timing_summary_rpt $::env(OUTPUT_DIR)/${design_name}${output_suffix}_timing_summary.rpt
puts "  Generating timing summary: $timing_summary_rpt"
if {[catch {
    set fp [open $timing_summary_rpt w]
    
    puts $fp "# Timing Summary for $design_name"
    puts $fp "# Generated by sta.tcl"
    puts $fp ""
    
    # Report clock information
    set clocks [get_clocks]
    puts $fp "Clocks:"
    foreach clk $clocks {
        set clk_name [get_name $clk]
        set period [get_property $clk period]
        puts $fp "  $clk_name: period = $period ns"
    }
    puts $fp ""
    
    # Try to get timing metrics (may not be available in all OpenROAD versions)
    puts $fp "Setup Timing:"
    if {[catch {
        set wns_setup [sta::worst_slack_cmd "max"]
        set tns_setup [sta::total_negative_slack_cmd "max"]
        puts $fp "  Worst Negative Slack (WNS): $wns_setup ns"
        puts $fp "  Total Negative Slack (TNS): $tns_setup ns"
    }]} {
        puts $fp "  (WNS/TNS values - see $setup_rpt for details)"
    }
    puts $fp ""
    
    puts $fp "Hold Timing:"
    if {[catch {
        set wns_hold [sta::worst_slack_cmd "min"]
        set tns_hold [sta::total_negative_slack_cmd "min"]
        puts $fp "  Worst Negative Slack (WNS): $wns_hold ns"
        puts $fp "  Total Negative Slack (TNS): $tns_hold ns"
    }]} {
        puts $fp "  (WNS/TNS values - see $hold_rpt for details)"
    }
    puts $fp ""
    
    puts $fp "Note: For detailed timing information, see:"
    puts $fp "  - Setup report: $setup_rpt"
    puts $fp "  - Hold report: $hold_rpt"
    puts $fp "  - Clock skew report: $skew_rpt"
    
    close $fp
    puts "    Timing summary generated"
} error_msg]} {
    puts "    Warning: Timing summary generation failed: $error_msg"
}

# Print summary to console
puts ""
puts "\[STA\] =========================================="
puts "\[STA\] Timing Analysis Summary"
puts "\[STA\] =========================================="
puts "  Design: $design_name"
puts "  Reports generated:"
puts "    - Setup:   $setup_rpt"
puts "    - Hold:    $hold_rpt"
puts "    - Skew:    $skew_rpt"
puts "    - Summary: $timing_summary_rpt"
puts "\[STA\] =========================================="
puts ""

puts "\[STA\] Completed."
