"""
eco_generator.py: Wrapper script to run the ECO flow.
"""
import sys
from pathlib import Path
from src.cts.htree_builder import run_eco_flow

def main():
    if len(sys.argv) > 1:
        design_name = sys.argv[1]
    else:
        design_name = "arith"
    
    # Define paths relative to project root
    # script is in src/eco_generator.py, so root is parent of parent
    project_root = Path(__file__).resolve().parent.parent
    
    netlist_path = project_root / f"inputs/designs/{design_name}_mapped.json"
    
    # Map file is generated by placer in build/<design_name>/<design_name>.map
    map_file_path = project_root / "build" / design_name / f"{design_name}.map"
    
    fabric_cells_path = project_root / "inputs/Platform/fabric_cells.yaml"
    fabric_path = project_root / "inputs/Platform/fabric.yaml"
    pins_path = project_root / "inputs/Platform/pins.yaml"
    
    output_dir = project_root / "build" / design_name
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"Running ECO flow for design: {design_name}")
    print(f"  Netlist: {netlist_path}")
    print(f"  Map file: {map_file_path}")
    
    if not map_file_path.exists():
        print(f"Error: Map file not found: {map_file_path}")
        print("Please run 'make placer' first.")
        sys.exit(1)
        
    run_eco_flow(
        design_name=design_name,
        netlist_path=str(netlist_path),
        map_file_path=str(map_file_path),
        fabric_cells_path=str(fabric_cells_path),
        fabric_path=str(fabric_path),
        output_dir=str(output_dir),
        pins_path=str(pins_path)
    )

if __name__ == "__main__":
    main()
